# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build & makeself & Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
          cache: true

      - name: Build bundle
        run: |

          GOOS=linux GOARCH=amd64 CGO_ENABLED=0  go build -v -ldflags="-w -s" -o ./dist/linux-amd64/main ./main.go
          cd ./dist/linux-amd64/
          tar  zcvf ../../dist/main-linux-amd64.tgz ./*
          cd ../../
      - run: |
          cd ./installer
          sudo apt update
          sudo apt install makeself    -y
          mkdir source
          cp ../dist/linux-amd64/main ./source/
          sh build.sh
          cp ./build/go_ws_sh_installer.run ../dist/
          mv ../dist/go_ws_sh_installer.run ../dist/go_ws_sh_installer-linux-amd64.run

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: Continuous-integration-${{ github.sha }}
          #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            dist/*.tgz
            dist/*.run
